### ISSUE TITLE
Create initial webview

### ISSUE THREAD

**Issue by jbdanquah2** [jbdanquah2/tuitelage#1]

**Comment by jbdanquah2** [comment]
Emma... I need updated version of the interface by Tuesday

**Comment by Mancunia** [comment]
@jbdanquah2  am changing the whole interface, check cisco academy's page, simple and easy to manage

**Comment by jbdanquah2** [comment]
Well noted... I also need you to make commits of what ever progress you've
made and push it to github so that we all clone and do our part


John Danquah-Boateng

Call: +233245052539
WhatsApp: +233245052539
Email: yjbdanquah@gmail.com

**Comment by jbdanquah2** [comment]
Emma... I need you to make use of Bootstrap 4 cards... its more beautiful and very easy to use..

**Comment by jbdanquah2** [comment]
this issue is done
